
package com.qiugui.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyservice", targetNamespace = "http://service.qiugui.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyservice {


    /**
     * 
     * @param parameters
     * @param authInfo
     * @return
     *     returns com.qiugui.service.ListResponse
     */
    @WebMethod
    @WebResult(name = "listResponse", targetNamespace = "http://service.qiugui.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.qiugui.com/IMyservice/listRequest", output = "http://service.qiugui.com/IMyservice/listResponse")
    public ListResponse list(
        @WebParam(name = "list", targetNamespace = "http://service.qiugui.com/", partName = "parameters")
        List parameters,
        @WebParam(name = "authInfo", targetNamespace = "http://service.qiugui.com/", header = true, partName = "authInfo")
        String authInfo);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.AddUserResponse")
    @Action(input = "http://service.qiugui.com/IMyservice/addUserRequest", output = "http://service.qiugui.com/IMyservice/addUserResponse")
    public void addUser(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<User> user);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.MinusResponse")
    @Action(input = "http://service.qiugui.com/IMyservice/minusRequest", output = "http://service.qiugui.com/IMyservice/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.qiugui.service.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.LoginResponse")
    @Action(input = "http://service.qiugui.com/IMyservice/loginRequest", output = "http://service.qiugui.com/IMyservice/loginResponse", fault = {
        @FaultAction(className = UserException_Exception.class, value = "http://service.qiugui.com/IMyservice/login/Fault/UserException")
    })
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException_Exception
    ;

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "plusResult", targetNamespace = "")
    @RequestWrapper(localName = "plus", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.Plus")
    @ResponseWrapper(localName = "plusResponse", targetNamespace = "http://service.qiugui.com/", className = "com.qiugui.service.PlusResponse")
    @Action(input = "http://service.qiugui.com/IMyservice/plusRequest", output = "http://service.qiugui.com/IMyservice/plusResponse")
    public int plus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
