
package com.qiugui.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyserviceImplService", targetNamespace = "http://service.qiugui.com/", wsdlLocation = "http://127.0.0.1:8888/ns?wsdl")
@HandlerChain(file="handler-chain.xml")
public class MyserviceImplService
    extends Service
{

    private final static URL MYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MYSERVICEIMPLSERVICE_QNAME = new QName("http://service.qiugui.com/", "MyserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/ns?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MyserviceImplService() {
        super(__getWsdlLocation(), MYSERVICEIMPLSERVICE_QNAME);
    }

    public MyserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICEIMPLSERVICE_QNAME);
    }

    public MyserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMyservice
     */
    @WebEndpoint(name = "MyserviceImplPort")
    public IMyservice getMyserviceImplPort() {
        return super.getPort(new QName("http://service.qiugui.com/", "MyserviceImplPort"), IMyservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMyservice
     */
    @WebEndpoint(name = "MyserviceImplPort")
    public IMyservice getMyserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.qiugui.com/", "MyserviceImplPort"), IMyservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
